catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.AllLoanedBooksListView.as_view(), name='all-borrowed'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew_book_librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name="author_create"),
    path('author/<int:pk>/update', views.AuthorUpdate.as_view(), name="author_update"),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name="author_delete"),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.urls import reverse
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import uuid
import datetime


# Create your models here.
class Language(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a Language")

    def __str__(self):
        return self.name


class Genre(models.Model):
    name = models.CharField(max_length=200, help_text="Enter a genre")

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True, help_text='Select a language for this book')
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character ISBN number')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        return ', '.join([genre.name for genre in self.genre.all()[:3]])
    display_genre.short_description = 'Genre'

    def count_available(self):
        return self.bookinstance_set.filter(status='a').count()


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this book")
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    LOAN_STATUS = (
        ('m', 'Maintainance'),
        ('o', 'On Loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book status')

    class Meta:
        ordering = ["due_back"]
        permissions = (('can_mark_returned', 'Set book as returned'),)

    def __str__(self):
        return '{0}({1})'.format(self.book.title, self.id)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Author(models.Model):

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField('Born', null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return '{0}, {1}'.format(self.last_name, self.first_name)


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3)")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if date is not in the past
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if date is in correct range (<4weeks)
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Book, Author, BookInstance
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from .models import RenewBookForm
import datetime


def index(request):
    """
    View function for home page of site.
    """
    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    # Available books (status = 'a')
    num_books_available = 0
    for book in Book.objects.all():
        num_books_available += book.bookinstance_set.filter(status='a').count()
    num_authors = Author.objects.count()  # The 'all()' is implied by default.

    # Number of visits to this view, as counted in the session variable
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    # Render the HTML template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={
            'num_books': num_books,
            'num_books_available': num_books_available,
            'num_authors': num_authors,
            'num_visits': num_visits
        },
    )


# to show the book list, using a predefined view
class BookListView(generic.ListView):
    model = Book


# To show the book  details, using a predefined view
class BookDetailView(generic.DetailView):
    model = Book


# To show the author list, using a predefined view
class AuthorListView(generic.ListView):
    model = Author


# To show the author detail, using a predefined view
class AuthorDetailView(generic.DetailView):
    model = Author


# To show the borrowed books, using a predefined view
class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status='o').order_by('due_back')


class AllLoanedBooksListView(PermissionRequiredMixin, generic.ListView):
    permission_required = 'catalog.can_mark_returned'
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_inst = get_object_or_404(BookInstance, pk=pk)

    # POST => process the form data
    if request.method == 'POST':
        # Validate data, populate with old values
        form = RenewBookForm(request.POST)

        # Check if valid
        if form.is_valid():
            # Now process
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            # Redirect to URL
            return HttpResponseRedirect(reverse('all-borrowed'))

    # If GET, give default first form
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    return render(request, 'catalog/book_renew_librarian.html', {'form': form, 'bookinst': book_inst})


# Author edit views generic
class AuthorCreate(CreateView):
    model = Author
    # fields can be specified like this
    fields = '__all__'
    # set initial values
    initial = {'date_of_death': '05/01/2018', }


class AuthorUpdate(UpdateView):
    model = Author
    # also like this
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']


class AuthorDelete(DeleteView):
    model = Author
    # by default this redirects to the author detail page
    # we want it to go to the author detail page
    success_url = reverse_lazy('authors')

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
  
  <h1>Delete Author</h1>
  <p>Are you sure you want to delete the author: {{ author }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" />
  </form>

{% endblock content %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}

  <h1>{{author.first_name}} {{author.last_name}}</h1>

  <p>{{author.date_of_birth}} - {% if author.date_of_death is not None %} {{author.date_of_death}} {% endif %}</p>
  <div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>
    <hr />
    <ul>
      {% for book in author.book_set.all %}
        <li>
          <p>
            <a href="{% url 'book-detail' pk=book.pk %}"><strong>{{book.title}}</strong></a> ({{book.count_available}} copies available)
          </p>
          <p>
            {{book.summary}}
          </p>
        </li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
 <form action="" method="post">
   {% csrf_token %}
   <table>
     {{ form.as_table }}
   </table>
   <input type="submit" value="Submit" />
 </form> 
{% endblock content %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Authors</h1>
  <hr />

  <ul>
    {% for author in author_list %}
      <li>
        <a href="{% url 'author-detail' pk=author.pk %}">{{author.last_name}}, {{author.first_name}}</a>  ({{author.book_set.count}} books)
      </li>
    {% endfor %}
  </ul>

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p>
    <strong>Author:</strong> <a href="{% url 'author-detail' pk=book.author.pk %}">{{ book.author }}</a>
  </p>
  <p>
    <strong>Summary:</strong> {{ book.summary }}
  </p>
  <p>
    <strong>ISBN:</strong> {{ book.isbn }}
  </p>
  <p>
    <strong>Language:</strong> {{ book.language }}
  </p>
  <p>
    <strong>Genre:</strong>
    {% for genre in book.genre.all %}
      {{ genre }}
      {% if not forloop.last %}, {% endif %}
    {% endfor %}
  </p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>

{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>

  {% if book_list %}
    <ul>
      {% for book in book_list %}
        <li>
          <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>
      There are no books in the library.
    </p>
  {% endif %}



{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}

  <h1>Renew: {{ bookinst.book.title }}</h1>
  <p>Borrower: {{ bookinst.borrower }}</p>
  <p {% if bookinst.is_overdue %} class="text-danger" {% endif %}}>Due date: {{ bookinst.due_back }} </p>
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form }}
    </table>
    <input type="submit" value="Submit" />
  </form>

{% endblock content %}

catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>All Borrowed Books</h1>

    <ul>
        {% for bookinst in bookinstance_list %}
        <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
            <a>{{bookinst.book.title}}</a>
            ({{bookinst.due_back}}) - {{bookinst.borrower}}
            {% if perms.catalog.can_mark_returned %}
              - <a href="{% url 'renew_book_librarian' bookinst.id %}">Renew</a>
            {% endif %}
        </li>
        
        {% endfor %}
    </ul>

{% endblock content %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}

  <h1>Borrowed Books</h1>

  {% if bookinstance_list %}
  <ul>
    {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">
                {{bookinst.book.title}}
        </a>
        ({{bookinst.due_back}})
      </li>
    {% endfor %}
  </ul>

    {% else %}
    <p>There are no borrowed books</p>
    {% endif %}

{% endblock %}